local sub = ubermenu:add_submenu({ title = "GOTY Server Management" })
	local sub1 = sub:add_submenu({ title = "Arena" })
		sub1:add_item({ title = "Air Arena",              func = function() openConsole("/srvlua Admin.Game.NextMap(1495)") end })
		sub1:add_item({ title = "Fraytown",               func = function() openConsole("/srvlua Admin.Game.NextMap(1545)") end })
		sub1:add_item({ title = "Hinterlands",            func = function() openConsole("/srvlua Admin.Game.NextMap(1533)") end })
		sub1:add_item({ title = "Lava Arena",             func = function() openConsole("/srvlua Admin.Game.NextMap(1498)") end })
		sub1:add_item({ title = "Undercroft",             func = function() openConsole("/srvlua Admin.Game.NextMap(1546)") end })
		sub1:add_item({ title = "Walled In",              func = function() openConsole("/srvlua Admin.Game.NextMap(1497)") end })
		sub1:add_item({ title = "Whiteout",               func = function() openConsole("/srvlua Admin.Game.NextMap(1544)") end })

	local sub1 = sub:add_submenu({ title = "Blitz" })
		sub1:add_item({ title = "Arx Novena",             func = function() openConsole("/srvlua Admin.Game.NextMap(2566)") end })
		sub1:add_item({ title = "Bella Omega",            func = function() openConsole("/srvlua Admin.Game.NextMap(1550)") end })
		sub1:add_item({ title = "Blueshift",              func = function() openConsole("/srvlua Admin.Game.NextMap(1552)") end })
		sub1:add_item({ title = "Canyon Crusade Revival", func = function() openConsole("/srvlua Admin.Game.NextMap(1549)") end })
		sub1:add_item({ title = "Crossfire",              func = function() openConsole("/srvlua Admin.Game.NextMap(1542)") end })
		sub1:add_item({ title = "Drydock",                func = function() openConsole("/srvlua Admin.Game.NextMap(2599)") end })
		sub1:add_item({ title = "Hellfire",               func = function() openConsole("/srvlua Admin.Game.NextMap(1561)") end })
		sub1:add_item({ title = "Katabatic",              func = function() openConsole("/srvlua Admin.Game.NextMap(2598)") end })

	local sub1 = sub:add_submenu({ title = "Capture and Hold" })
		sub1:add_item({ title = "Canyon Crusade Revival", func = function() openConsole("/srvlua Admin.Game.NextMap(1548)") end })
		sub1:add_item({ title = "Drydock Night",          func = function() openConsole("/srvlua Admin.Game.NextMap(1530)") end })
		sub1:add_item({ title = "Katabatic",              func = function() openConsole("/srvlua Admin.Game.NextMap(1521)") end })
		sub1:add_item({ title = "Outskirts 3P",           func = function() openConsole("/srvlua Admin.Game.NextMap(1526)") end })
		sub1:add_item({ title = "Raindance",              func = function() openConsole("/srvlua Admin.Game.NextMap(1528)") end })
		sub1:add_item({ title = "Sulfurcove",             func = function() openConsole("/srvlua Admin.Game.NextMap(1535)") end })
		sub1:add_item({ title = "Tartarus",               func = function() openConsole("/srvlua Admin.Game.NextMap(1537)") end })

	local sub1 = sub:add_submenu({ title = "Capture the Flag" })
		sub1:add_item({ title = "Arx Novena",             func = function() openConsole("/srvlua Admin.Game.NextMap(1456)") end })
		sub1:add_item({ title = "Bella Omega",            func = function() openConsole("/srvlua Admin.Game.NextMap(1573)") end })
		sub1:add_item({ title = "Bella Omega NS",         func = function() openConsole("/srvlua Admin.Game.NextMap(1551)") end })
		sub1:add_item({ title = "Blueshift",              func = function() openConsole("/srvlua Admin.Game.NextMap(1543)") end })
		sub1:add_item({ title = "Canyon Crusade Revival", func = function() openConsole("/srvlua Admin.Game.NextMap(1514)") end })
		sub1:add_item({ title = "Crossfire",              func = function() openConsole("/srvlua Admin.Game.NextMap(1462)") end })
		sub1:add_item({ title = "Dangerous Crossing",     func = function() openConsole("/srvlua Admin.Game.NextMap(1538)") end })
		sub1:add_item({ title = "Drydock",                func = function() openConsole("/srvlua Admin.Game.NextMap(1457)") end })
		sub1:add_item({ title = "Hellfire",               func = function() openConsole("/srvlua Admin.Game.NextMap(1560)") end })
		sub1:add_item({ title = "Icecoaster",             func = function() openConsole("/srvlua Admin.Game.NextMap(1554)") end })
		sub1:add_item({ title = "Katabatic",              func = function() openConsole("/srvlua Admin.Game.NextMap(1447)") end })
		sub1:add_item({ title = "Perdition",              func = function() openConsole("/srvlua Admin.Game.NextMap(1555)") end })
		sub1:add_item({ title = "Permafrost",             func = function() openConsole("/srvlua Admin.Game.NextMap(1534)") end })
		sub1:add_item({ title = "Raindance",              func = function() openConsole("/srvlua Admin.Game.NextMap(1516)") end })
		sub1:add_item({ title = "Stonehenge",             func = function() openConsole("/srvlua Admin.Game.NextMap(1522)") end })
		sub1:add_item({ title = "Sunstar",                func = function() openConsole("/srvlua Admin.Game.NextMap(1523)") end })
		sub1:add_item({ title = "Tartarus",               func = function() openConsole("/srvlua Admin.Game.NextMap(1512)") end })
		sub1:add_item({ title = "Temple Ruins",           func = function() openConsole("/srvlua Admin.Game.NextMap(1493)") end })
		sub1:add_item({ title = "Terminus",               func = function() openConsole("/srvlua Admin.Game.NextMap(1553)") end })

	local sub1 = sub:add_submenu({ title = "Rabbit" })
		sub1:add_item({ title = "Crossfire",              func = function() openConsole("/srvlua Admin.Game.NextMap(1464)") end })
		sub1:add_item({ title = "Inferno",                func = function() openConsole("/srvlua Admin.Game.NextMap(1491)") end })
		sub1:add_item({ title = "Nightabatic",            func = function() openConsole("/srvlua Admin.Game.NextMap(1494)") end })
		sub1:add_item({ title = "Outskirts",              func = function() openConsole("/srvlua Admin.Game.NextMap(1458)") end })
		sub1:add_item({ title = "Quicksand",              func = function() openConsole("/srvlua Admin.Game.NextMap(1461)") end })
		sub1:add_item({ title = "Sulfur Cove",            func = function() openConsole("/srvlua Admin.Game.NextMap(1496)") end })

	local sub1 = sub:add_submenu({ title = "Team Deathmatch" })
		sub1:add_item({ title = "Crossfire",              func = function() openConsole("/srvlua Admin.Game.NextMap(1482)") end })
		sub1:add_item({ title = "Drydock Night",          func = function() openConsole("/srvlua Admin.Game.NextMap(1480)") end })
		sub1:add_item({ title = "Inferno",                func = function() openConsole("/srvlua Admin.Game.NextMap(1487)") end })
		sub1:add_item({ title = "Miasma",                 func = function() openConsole("/srvlua Admin.Game.NextMap(1536)") end })
		sub1:add_item({ title = "Nightabatic",            func = function() openConsole("/srvlua Admin.Game.NextMap(1485)") end })
		sub1:add_item({ title = "Outskirts",              func = function() openConsole("/srvlua Admin.Game.NextMap(1490)") end })
		sub1:add_item({ title = "Quicksand",              func = function() openConsole("/srvlua Admin.Game.NextMap(1484)") end })
		sub1:add_item({ title = "Sulfur Cove",            func = function() openConsole("/srvlua Admin.Game.NextMap(1488)") end })

	sub:add_separator({})
	sub:add_item({ title = "End Current Map",             func = function() openConsole("/srvlua Admin.Game.EndMap()") end })
	sub:add_item({ title = "Skip Warmup",                 func = function() openConsole("/srvlua Admin.Game.StartMap()") end })

	sub:add_separator({ title = "Server" })
	sub:add_item({ title = "Send Console Message",        func = function() openConsole("/srvlua Admin.SendConsoleMessageToAllPlayers(\"MESSAGE\")") end })
	sub:add_item({ title = "Send Game Message",           func = function() openConsole("/srvlua Admin.SendGameMessageToAllPlayers(\"MESSAGE\", 2.0)") end })
	sub:add_variable({ title = "Server Login Role", varname = "srvloginrole", default = "admin" })
	sub:add_item({ title = "Login",                       func = function() openConsole("/srvlogin " ..  srvloginrole .. " ") end })

sub = nil
sub1 = nil
